#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-logging-log4j2
Version  : log4j.2.7
Release  : 1
URL      : https://github.com/apache/logging-log4j2/archive/log4j-2.7.tar.gz
Source0  : https://github.com/apache/logging-log4j2/archive/log4j-2.7.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-api/2.7/log4j-api-2.7.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-api/2.7/log4j-api-2.7.pom
Source3  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-api/2.9.1/log4j-api-2.9.1.jar
Source4  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-api/2.9.1/log4j-api-2.9.1.pom
Source5  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-core/2.7/log4j-core-2.7.jar
Source6  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-core/2.7/log4j-core-2.7.pom
Source7  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-core/2.9.1/log4j-core-2.9.1.jar
Source8  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-core/2.9.1/log4j-core-2.9.1.pom
Source9  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-to-slf4j/2.7/log4j-to-slf4j-2.7.jar
Source10  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-to-slf4j/2.7/log4j-to-slf4j-2.7.pom
Source11  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-to-slf4j/2.9.1/log4j-to-slf4j-2.9.1.jar
Source12  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-to-slf4j/2.9.1/log4j-to-slf4j-2.9.1.pom
Source13  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j/2.7/log4j-2.7.pom
Source14  : https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j/2.9.1/log4j-2.9.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-logging-log4j2-data = %{version}-%{release}
Requires: mvn-logging-log4j2-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
# [Apache Log4j 2](http://logging.apache.org/log4j/2.x/)
Apache Log4j 2 is an upgrade to Log4j that provides significant improvements over its predecessor, Log4j 1.x,
and provides many of the improvements available in Logback while fixing some inherent problems in Logback's architecture.

%package data
Summary: data components for the mvn-logging-log4j2 package.
Group: Data

%description data
data components for the mvn-logging-log4j2 package.


%package license
Summary: license components for the mvn-logging-log4j2 package.
Group: Default

%description license
license components for the mvn-logging-log4j2 package.


%prep
%setup -q -n logging-log4j2-log4j-2.7

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-logging-log4j2
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-logging-log4j2/LICENSE.txt
cp log4j-core/src/main/resources/META-INF/LICENSE %{buildroot}/usr/share/package-licenses/mvn-logging-log4j2/log4j-core_src_main_resources_META-INF_LICENSE
cp log4j-core/src/main/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/mvn-logging-log4j2/log4j-core_src_main_resources_META-INF_NOTICE
cp log4j-core/src/test/resources/META-INF/LICENSE %{buildroot}/usr/share/package-licenses/mvn-logging-log4j2/log4j-core_src_test_resources_META-INF_LICENSE
cp log4j-core/src/test/resources/META-INF/NOTICE %{buildroot}/usr/share/package-licenses/mvn-logging-log4j2/log4j-core_src_test_resources_META-INF_NOTICE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.7
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.7/log4j-api-2.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.7
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.7/log4j-api-2.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.9.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.9.1/log4j-api-2.9.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.9.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.9.1/log4j-api-2.9.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.7
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.7/log4j-core-2.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.7
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.7/log4j-core-2.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.9.1
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.9.1/log4j-core-2.9.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.9.1
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.9.1/log4j-core-2.9.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.7
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.7/log4j-to-slf4j-2.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.7
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.7/log4j-to-slf4j-2.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.9.1
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.9.1/log4j-to-slf4j-2.9.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.9.1
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.9.1/log4j-to-slf4j-2.9.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j/2.7
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j/2.7/log4j-2.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j/2.9.1
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j/2.9.1/log4j-2.9.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.7/log4j-api-2.7.jar
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.7/log4j-api-2.7.pom
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.9.1/log4j-api-2.9.1.jar
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-api/2.9.1/log4j-api-2.9.1.pom
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.7/log4j-core-2.7.jar
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.7/log4j-core-2.7.pom
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.9.1/log4j-core-2.9.1.jar
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-core/2.9.1/log4j-core-2.9.1.pom
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.7/log4j-to-slf4j-2.7.jar
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.7/log4j-to-slf4j-2.7.pom
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.9.1/log4j-to-slf4j-2.9.1.jar
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.9.1/log4j-to-slf4j-2.9.1.pom
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j/2.7/log4j-2.7.pom
/usr/share/java/.m2/repository/org/apache/logging/log4j/log4j/2.9.1/log4j-2.9.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-logging-log4j2/LICENSE.txt
/usr/share/package-licenses/mvn-logging-log4j2/log4j-core_src_main_resources_META-INF_LICENSE
/usr/share/package-licenses/mvn-logging-log4j2/log4j-core_src_main_resources_META-INF_NOTICE
/usr/share/package-licenses/mvn-logging-log4j2/log4j-core_src_test_resources_META-INF_LICENSE
/usr/share/package-licenses/mvn-logging-log4j2/log4j-core_src_test_resources_META-INF_NOTICE
